name: AppRunner
permissions: read-all

on:
  push:
    branches: ['main']
    paths:
      - 'app-runner/**'
      - '.github/workflows/app-runner.yml'
      - '.github/workflows/test-powershell-module.yml'
      - 'PSScriptAnalyzerSettings.psd1'
  pull_request:
    branches: ['main']
    paths:
      - 'app-runner/**'
      - '.github/workflows/app-runner.yml'
      - '.github/workflows/test-powershell-module.yml'
      - 'PSScriptAnalyzerSettings.psd1'

jobs:
  test:
    uses: ./.github/workflows/test-powershell-module.yml
    secrets: inherit
    with:
      module-name: SentryAppRunner
      module-path: app-runner
      test-path: Tests
      exclude-path: Adb.Tests.ps1
      settings-path: PSScriptAnalyzerSettings.psd1

  test-adb:
    uses: ./.github/workflows/test-adb-provider.yml
    with:
      module-path: app-runner
