name: AppRunner

on:
  push:
    branches: ['main']
    paths:
      - 'app-runner/**'
      - '.github/workflows/app-runner.yml'
      - '.github/workflows/test-powershell-module.yml'
      - 'PSScriptAnalyzerSettings.psd1'
  pull_request:
    branches: ['main']
    paths:
      - 'app-runner/**'
      - '.github/workflows/app-runner.yml'
      - '.github/workflows/test-powershell-module.yml'
      - 'PSScriptAnalyzerSettings.psd1'

jobs:
  test:
    uses: ./.github/workflows/test-powershell-module.yml
    with:
      module-name: SentryAppRunner
      module-path: app-runner
      test-path: Tests
      settings-path: PSScriptAnalyzerSettings.psd1
