name: SentryApiClient

on:
  push:
    branches: ['main']
    paths:
      - 'sentry-api-client/**'
      - '.github/workflows/sentry-api-client.yml'
      - '.github/workflows/test-powershell-module.yml'
      - 'PSScriptAnalyzerSettings.psd1'
  pull_request:
    branches: ['main']
    paths:
      - 'sentry-api-client/**'
      - '.github/workflows/sentry-api-client.yml'
      - '.github/workflows/test-powershell-module.yml'
      - 'PSScriptAnalyzerSettings.psd1'

jobs:
  test:
    uses: ./.github/workflows/test-powershell-module.yml
    with:
      module-name: SentryApiClient
      module-path: sentry-api-client
      test-path: Tests
      settings-path: PSScriptAnalyzerSettings.psd1
